Include ENL function to Update utils_metrics.R
Jean-Romain/lidR pull request #380
Opened 2020-10-01 23:41 UTC by lhambrecht

Added function to calculate Effective Number of Layers (ENL) based on the method by Ehbrecht et al. 2016. ENL included Hill number 0D, 1D, 2D. 1D is based on the Shannon diversity index while 2D is based on the Simpson diversity index. 
Empty layers are not removed which will lead to empty cells when 1D is calculated with `grid_metrics`.

ALS and space-borne LiDAR papers often use the foliage height diversity [FHD] (based on Shannon diversity index) to assess the vertical forest structure. However, because Shannon diversity indices rely on the natural log it can not deal with empty layers. This is a really issue for high point density point clouds such as from UAV based LiDAR, dens forest due to occlusion and forest with gaps in the vertical structure.
Ehbrecht et al. proposed the ENL based on TLS scan but can be applied to ALS as well. ENL is more intuitive then FHD which is a common criticism. Furthermore, 2D ENL is based on the Simpson diversity index which is not based on the natural log and therefore can deal with empty layers. This makes it more suitable for high point density. The scalability of ENL is currently being explored but first impression seem to be promising to be able to scale ENL from TLS to ALS and even space-borne lidar.

Code needs to be reviewed but I try to based it on the entropy function.

2020-10-02 00:55 UTC, Jean-Romain requested changes
Thank you for integrating your work in `lidR`. Sadly, as is, I cannot accept the PR. I put many comments + here a list of thing do to:

- [ ] Generate the `Rd` file of the documentation to check that you documentation is valid (it is not). And include the Rd file in the PR
- [ ] Write unit tests in `test/testthat/test-metrics.R`. Do not take example on the existing tests in this file they are weak. Your test must ensure that your function fails properly when needed, returns the good value in all cases, test limit cases with unexpected data and so on...
- [ ] Run `R CMD check`.  As is your PR fails CRAN checks
- [ ] Add examples in the doc.
- [ ] Update contributors in `DESCRIPTION` files.

Also I only looked at section 2.2.2.1 quickly in the paper. I see:

> where p_i is the proportion of filled voxels in the ith vertical layer to the sum of filled voxel in the entire volume analyzed.

Which is definitively not what is computed here. Please explain me. 

Thanks.

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +  if (D > 2)
The same. Actually the function should start with assertions. See`utils_assertive.R`

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +  hist = findInterval(z, bk)
Your function will fails I guess if some `z < 0` right? Unit tests will tell us.

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +  if(D==2){
Simplify conditional statements. Use `if () { } else if ()  { } else { }` or `if () return if () return if() return`

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +      enl <- sum(p^0) #0D ENL formula
Hmm this is equivalent to `length(p)` right?

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +      stop("D must be 0,1 or 2.") #Error
Should be tested *before* to perform any costly computation and throw an error

2020-10-02 00:55 UTC, Jean-Romain commented on R/utils_metrics.R
> +#' @export ENL
Missing `@examples`

2020-10-02 01:10 UTC, lhambrecht commented
Thanks for the feedback. This is much appreciated since this is my first time contributing on GitHub.
I will try to address these issue the best I can.
BTW, congratulations on the paper!

2020-10-27 16:17 UTC, Jean-Romain commented
This PR has been opened 1 month ago. Do you plan to finalize the PR or can I close it?

2020-10-30 10:33 UTC, closed without merging